#!/usr/bin/env bash
# Stop hook: when Claude finishes a turn, review the uncommitted changes in the
# repo with a headless Claude and write the result to planning/REVIEW.md.
#
# - Skips when the working tree has no changes (other than REVIEW.md itself).
# - Skips when the changes are identical to the ones last reviewed.
# - Untracked files that look like secrets are never sent to the model.
# - The nested `claude -p` runs with hooks disabled so it cannot recurse.

set -u

[ "${CLAUDE_REVIEW_HOOK:-}" = "1" ] && exit 0

cd "$(dirname "$0")/../.." || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

REVIEW_FILE="planning/REVIEW.md"
STATE_FILE=".claude/hooks/.last-review-hash"
LOG_FILE=".claude/hooks/review.log"
MAX_DIFF_BYTES=200000
MODEL="${REVIEW_MODEL:-sonnet}"
EXCLUDE=":(exclude)$REVIEW_FILE"

untracked_files() {
  git ls-files --others --exclude-standard -- . "$EXCLUDE" |
    grep -viE '(^|/)\.env|\.(pem|key|p12|pfx)$|secret|credential|id_rsa'
}

collect_diff() {
  git --no-pager diff --no-color HEAD -- . "$EXCLUDE"
  untracked_files | while IFS= read -r f; do
    # --no-index exits 1 when files differ, which is always the case here
    git --no-pager diff --no-color --no-index -- /dev/null "$f" || true
  done
}

DIFF="$(collect_diff)"
[ -z "$DIFF" ] && exit 0

HASH="$(printf '%s' "$DIFF" | git hash-object --stdin)"
[ -f "$STATE_FILE" ] && [ "$(cat "$STATE_FILE")" = "$HASH" ] && exit 0

if [ "$(printf '%s' "$DIFF" | wc -c)" -gt "$MAX_DIFF_BYTES" ]; then
  DIFF="$(printf '%s' "$DIFF" | head -c "$MAX_DIFF_BYTES")

[... diff truncated at $MAX_DIFF_BYTES bytes; later files are not shown ...]"
fi

STAT="$(git --no-pager diff --stat HEAD -- . "$EXCLUDE"; untracked_files | sed 's/^/ new file: /')"

PROMPT="You are reviewing the latest uncommitted changes in the FinAlly project (spec: planning/PLAN.md).
Review the diff below for correctness bugs, deviations from the plan, security issues, missing tests, and simplification opportunities.
Output ONLY the Markdown for the review file, starting with the heading '# Review of latest changes'.
Include: a one-line summary, a 'Files changed' list, then findings grouped by severity (High / Medium / Low), each with file:line and a concrete fix. Say explicitly if nothing significant was found.

## Changed files
$STAT

## Diff
$DIFF"

TMP="$(mktemp)"
if printf '%s' "$PROMPT" |
   CLAUDE_REVIEW_HOOK=1 claude -p --model "$MODEL" --no-session-persistence \
     --settings '{"disableAllHooks":true}' > "$TMP" 2>"$LOG_FILE" && [ -s "$TMP" ]; then
  {
    printf '<!-- Generated by .claude/hooks/review-changes.sh on %s -->\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    cat "$TMP"
  } > "$REVIEW_FILE"
  printf '%s' "$HASH" > "$STATE_FILE"
fi
rm -f "$TMP"
exit 0
